title: Swarit
email: swarit31@gmail.com
favicon: true
color-scheme: auto

remote_theme: vaibhavvikas/jekyll-theme-minimalistic

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

navigation:
  - name: Home
    link: ./
  - name: Education
    link: ./education/
  - name: Experience
    link: ./experience/
  - name: Projects
    link: ./projects/
  - name: Publications
    link: ./publications/
  - name: Certifications
    link: ./certifications/

platforms:
  - name: Github
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/Swarit31
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/swarit-chaudhari/
  - name: ORCID
    icon: <i class="fa-brands fa-orcid"></i>
    link: https://orcid.org/0000-0003-3228-5939
