title: Swarit Chaudhari
email: swarit31@gmail.com
description: Mechanical Engineering | Non-Conventional Manufacturing | Controls | Process Optimization

markdown: kramdown
kramdown:
  input: GFM

permalink: pretty

navigation:
  - name: Home
    link: /
  - name: Education
    link: /education/
  - name: Experience
    link: /experience/
  - name: Projects
    link: /projects/
  - name: Publications
    link: /publications/
  - name: Certifications
    link: /certifications/

platforms:
  - name: GitHub
    link: https://github.com/Swarit31
  - name: LinkedIn
    link: https://www.linkedin.com/in/swarit-chaudhari/
  - name: ORCID
    link: https://orcid.org/0000-0003-3228-5939
